### ISSUE TITLE
Improve UX of bad config file in JetBrains

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord#1028]
Right now it shows something like error `BEGIN_OBJECT` - should provide concise error - "config file parse failed with error:"

**Comment by infiniteregrets** [comment]
I am not sure when this happens, but when I create a bad schema like provide a number for target instead of string it just gives me exception from mirrord cli nothing like `BEGIN_OBJECT `. Is there any particular thing that you add so that it gives that error?

**Comment by aviramha** [comment]
> I am not sure when this happens, but when I create a bad schema like provide a number for target instead of string it just gives me exception from mirrord cli nothing like `BEGIN_OBJECT `. Is there any particular thing that you add so that it gives that error?

Did you try it from JetBrains? Can you screenshot how it looked like?

**Comment by infiniteregrets** [comment]
> > I am not sure when this happens, but when I create a bad schema like provide a number for target instead of string it just gives me exception from mirrord cli nothing like `BEGIN_OBJECT `. Is there any particular thing that you add so that it gives that error?
> 
> Did you try it from JetBrains? Can you screenshot how it looked like?
<img width="820" alt="Screen Shot 2023-02-09 at 9 12 59 AM" src="https://user-images.githubusercontent.com/65443164/217836656-082a51aa-be13-40d2-b53a-8eb19ee088bb.png">

yes i tried on jetbrains

**Comment by aviramha** [comment]
That's still not a cool UX and I think it shows only when running on debug (i.e it's a crash report)
I was talking about the error notification "failed to run" in the left part of the screen

**Comment by infiniteregrets** [comment]
this time I got no failed run, used the same config, same project. I guess we can just catch the exception

<img width="1440" alt="Screen Shot 2023-02-09 at 12 00 54 PM" src="https://user-images.githubusercontent.com/65443164/217885197-28fb1b10-3431-4d7c-bc66-e3f6a3c09ce9.png">

```
Failed to execute debug configuration async

com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected name at line 11 column 6 path $.feature.
	at com.google.gson.Gson.fromJson(Gson.java:1229)
	at com.google.gson.Gson.fromJson(Gson.java:1124)
	at com.google.gson.Gson.fromJson(Gson.java:1034)
	at com.google.gson.Gson.fromJson(Gson.java:969)
	at com.metalbear.mirrord.MirrordConfigAPI.getConfigData(MirrordConfigAPI.kt:69)
	at com.metalbear.mirrord.MirrordConfigAPI.getTarget(MirrordConfigAPI.kt:76)
	at com.metalbear.mirrord.MirrordConfigAPI.isTargetSet(MirrordConfigAPI.kt:93)
	at com.metalbear.mirrord.MirrordExecManager.start(MirrordExecManager.kt:49)
	at com.metalbear.mirrord.products.idea.IdeaRunConfigurationExtension.patchEnv(IdeaRunConfigurationExtension.kt:40)
	at com.metalbear.mirrord.products.idea.IdeaRunConfigurationExtension.updateJavaParameters(IdeaRunConfigurationExtension.kt:54)
	at com.intellij.execution.JavaRunConfigurationExtensionManager.updateJavaParameters(JavaRunConfigurationExtensionManager.kt:42)
	at com.intellij.execution.application.BaseJavaApplicationCommandLineState.lambda$setupJavaParameters$0(BaseJavaApplicationCommandLineState.java:39)
	at com.intellij.openapi.application.ReadAction.lambda$run$1(ReadAction.java:59)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:873)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:68)
	at com.intellij.openapi.application.ReadAction.run(ReadAction.java:58)
	at com.intellij.execution.application.BaseJavaApplicationCommandLineState.setupJavaParameters(BaseJavaApplicationCommandLineState.java:38)
	at com.intellij.execution.application.ApplicationCommandLineState.createJavaParameters(ApplicationCommandLineState.java:41)
	at com.intellij.execution.configurations.JavaCommandLineState.getJavaParameters(JavaCommandLineState.java:41)
	at com.intellij.debugger.impl.GenericDebuggerRunner.lambda$doExecuteAsync$4(GenericDebuggerRunner.java:97)
	at com.intellij.execution.target.TargetEnvironmentAwareRunProfileState$1.run(TargetEnvironmentAwareRunProfileState.java:58)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:425)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:476)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:190)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:666)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:622)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:590)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:177)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.google.gson.stream.MalformedJsonException: Expected name at line 11 column 6 path $.feature.
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1657)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:514)
	at com.google.gson.stream.JsonReader.skipValue(JsonReader.java:1254)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:389)
	at com.google.gson.Gson.fromJson(Gson.java:1214)
	... 40 more

```

**Comment by infiniteregrets** [comment]
@aviramha can this be closed now?
