### ISSUE TITLE
Incompatible cpython `.so`s when SIP-patching python

### ISSUE THREAD

**Issue by t4lz** [metalbear-co/mirrord#1272]
### Bug Description

When running a SIP-protected python binary (i.e. when the binary itself is SIP protected, not when the python executable is a script with a SIP-protected shebang like `#!/usr/bin/env bash`), and a python script tries to import certain modules, there is an exception, because the patched binary is x86-64 and the available libraries are arm64.

I think this would be solved by #1155, right?

### Steps to Reproduce

1. `cd tests/python-e2e`
2. `mirrord exec --fs-mode=local --target deployment/py-serv-deployment /usr/bin/python3 -- -m uvicorn app_fastapi:app --host 0.0.0.0 --port 80 --root-path /`

### Backtrace

```shell
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/tal/Library/Python/3.9/lib/python/site-packages/uvicorn/__main__.py", line 4, in <module>
    uvicorn.main()
  File "/Users/tal/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/tal/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/tal/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/tal/Library/Python/3.9/lib/python/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/tal/Library/Python/3.9/lib/python/site-packages/uvicorn/main.py", line 403, in main
    run(
  File "/Users/tal/Library/Python/3.9/lib/python/site-packages/uvicorn/main.py", line 568, in run
    server.run()
  File "/Users/tal/Library/Python/3.9/lib/python/site-packages/uvicorn/server.py", line 59, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/tal/Library/Python/3.9/lib/python/site-packages/uvicorn/server.py", line 66, in serve
    config.load()
  File "/Users/tal/Library/Python/3.9/lib/python/site-packages/uvicorn/config.py", line 471, in load
    self.loaded_app = import_from_string(self.app)
  File "/Users/tal/Library/Python/3.9/lib/python/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/Users/tal/Library/Python/3.9/lib/python/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/tal/Documents/projects/mirrord/tests/python-e2e/app_fastapi.py", line 3, in <module>
    from fastapi import FastAPI, Response
  File "/Users/tal/Library/Python/3.9/lib/python/site-packages/fastapi/__init__.py", line 7, in <module>
    from .applications import FastAPI as FastAPI
  File "/Users/tal/Library/Python/3.9/lib/python/site-packages/fastapi/applications.py", line 16, in <module>
    from fastapi import routing
  File "/Users/tal/Library/Python/3.9/lib/python/site-packages/fastapi/routing.py", line 22, in <module>
    from fastapi import params
  File "/Users/tal/Library/Python/3.9/lib/python/site-packages/fastapi/params.py", line 4, in <module>
    from pydantic.fields import FieldInfo, Undefined
ImportError: dlopen(/Users/tal/Library/Python/3.9/lib/python/site-packages/pydantic/__init__.cpython-39-darwin.so, 0x0002): tried: '/Users/tal/Library/Python/3.9/lib/python/site-packages/pydantic/__init__.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/tal/Library/Python/3.9/lib/python/site-packages/pydantic/__init__.cpython-39-darwin.so' (no such file), '/Users/tal/Library/Python/3.9/lib/python/site-packages/pydantic/__init__.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
```

### Your operating system and version

macOS 13.3

### Local process

```
/usr/bin/python3: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64e:Mach-O 64-bit executable arm64e]
/usr/bin/python3 (for architecture x86_64):	Mach-O 64-bit executable x86_64
/usr/bin/python3 (for architecture arm64e):	Mach-O 64-bit executable arm64e
```

### Local process version

Python 3.9.6

**Comment by aviramha** [comment]
It depends if the `/usr/bin/python3` is the actual process - on macOS I think it's a launcher and not the actual Python binary, since if it's the real Python binary it won't work since it contains only x64 + arm64e (no arm64 to use..)

**Comment by t4lz** [comment]
According to mirrord's logs, `/usr/bin/python3` (or actually its patched version) executes `/Library/Developer/CommandLineTools/usr/bin/python3`, which then executes `/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/Resources/Python.app/Contents/MacOS/Python`, which gets the exception.

```
% ls -la /Library/Developer/CommandLineTools/usr/bin/python3
lrwxr-xr-x  1 root  wheel  67 Apr  2 09:18 /Library/Developer/CommandLineTools/usr/bin/python3 -> ../../Library/Frameworks/Python3.framework/Versions/3.9/bin/python3
```

```
% file /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/bin/python3.9
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/bin/python3.9: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64:Mach-O 64-bit executable arm64]
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/bin/python3.9 (for architecture x86_64):	Mach-O 64-bit executable x86_64
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/bin/python3.9 (for architecture arm64):	Mach-O 64-bit executable arm64
```

```
% file /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/Resources/Python.app/Contents/MacOS/Python
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/Resources/Python.app/Contents/MacOS/Python: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64:Mach-O 64-bit executable arm64]
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/Resources/Python.app/Contents/MacOS/Python (for architecture x86_64):	Mach-O 64-bit executable x86_64
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/Resources/Python.app/Contents/MacOS/Python (for architecture arm64):	Mach-O 64-bit executable arm64
```

**Comment by t4lz** [comment]
This is not going to be solved by #1155 (#1283), as the binary that is patched is `/usr/bin/python3` and that fat binary does not contain an arm64 binary.

**Comment by t4lz** [comment]
Yeah, but that file is not affected by what we do in sip patching, we don't patch it.

**Comment by aviramha** [comment]
Haven't seen this in a while so I believe this is fixed.
