### ISSUE TITLE
Flaky test: unpause_after_error

### ISSUE THREAD

**Issue by eyalb181** [metalbear-co/mirrord#1288]
### Bug Description

See logs here:
https://github.com/metalbear-co/mirrord/actions/runs/4682112027/jobs/8295682298

### Steps to Reproduce

N/A

### Your operating system and version

N/A

### Local process

N/A

**Comment by infiniteregrets** [comment]
here's a reproduced version of this error:
```
running 1 test
2023-05-14T22:26:07.956748Z creating service "pytest-echo" in namespace "random-namespace-7imdanu"
2023-05-14T22:26:28.129576Z done creating service "pytest-echo" in namespace "random-namespace-7imdanu"
Running local app with mirrord.
executed mirrord with args ["exec", "--target", "pod/pytest-echo-5zifj0o-848b7847df-v59kw/container/test", "-c", "--target-namespace", "random-namespace-7imdanu", "--", "grep", "nothing"] pid 49454
stdout 2023-05-14T22:26:28.943874Z 49454: mirrord cli starting

stderr 2023-05-14T22:26:28.944204Z 49454: 2023-05-14T22:26:28.944003Z  INFO mirrord: Launching "grep" with arguments ["nothing"]

stderr 2023-05-14T22:26:28.944295Z 49454: 2023-05-14T22:26:28.944268Z  WARN mirrord: Accepting invalid certificates

stdout 2023-05-14T22:26:28.944336Z 49454: preparing to launch process

stderr 2023-05-14T22:26:28.944774Z 49454: 2023-05-14T22:26:28.944743Z  WARN mirrord_config::config::unstable: Warning: field AgentConfig.pause is marked as unstable. Please note API may change
2023-05-14T22:26:28.944754Z  WARN mirrord_config::config::unstable: Warning: field AgentConfig.test_error is marked as unstable. Please note API may change

stderr 2023-05-14T22:26:28.944960Z 49454: 2023-05-14T22:26:28.944921Z  WARN mirrord: --pause specified without --steal: Incoming requests to the application will
                                           not be handled. The target container running the deployed application is paused,
                                           and responses from the local application are dropped.

                                           Attention: if network based liveness/readiness probes are defined for the
                                           target, they will fail under this configuration.

                                           To have the local application handle incoming requests you can run again with
                                           `--steal`. To have the deployed application handle requests, run again without
                                           specifying `--pause`.
    

stdout 2023-05-14T22:26:28.945012Z 49454: extracting layer

stderr 2023-05-14T22:26:28.983164Z 49454: 2023-05-14T22:26:28.983078Z DEBUG mirrord::extract: Extracted library file to "/tmp/8418494596008459107-libmirrord_layer.dylib"

stdout 2023-05-14T22:26:28.983221Z 49454: layer extracted
Checking Operator

stderr 2023-05-14T22:26:28.999110Z 49454: 2023-05-14T22:26:28.999036Z  WARN kube_client::client::tls::rustls_tls: Server cert bypassed

stderr 2023-05-14T22:26:29.002747Z 49454: 2023-05-14T22:26:29.002669Z  WARN kube_client::client: Unsuccessful data error parse: 404 page not found


stdout 2023-05-14T22:26:29.002834Z 49454: No Operator Detected

stderr 2023-05-14T22:26:29.013789Z 49454: 2023-05-14T22:26:29.013708Z  WARN kube_client::client::tls::rustls_tls: Server cert bypassed

stderr 2023-05-14T22:26:29.019641Z 49454: 2023-05-14T22:26:29.019578Z  INFO mirrord_kube::api::kubernetes: No existing agent, spawning new one.

stderr 2023-05-14T22:26:29.019745Z 49454: 2023-05-14T22:26:29.019707Z  INFO mirrord_kube::api::kubernetes: Using port `43264` for communication
2023-05-14T22:26:29.019714Z  INFO mirrord_kube::api::kubernetes: Using group-id `55837`

stdout 2023-05-14T22:26:29.019773Z 49454: creating agent pod...

stdout 2023-05-14T22:26:29.024728Z 49454: agent pod created
waiting for pod to be ready...

stderr 2023-05-14T22:26:29.109494Z 49454: 2023-05-14T22:26:29.109435Z DEBUG mirrord_kube::api::container: Pod Phase = "Pending"

stderr 2023-05-14T22:26:29.109977Z 49454: 2023-05-14T22:26:29.109921Z DEBUG mirrord_kube::api::container: Pod Phase = "Pending"

stderr 2023-05-14T22:26:30.247552Z 49454: 2023-05-14T22:26:30.247436Z DEBUG mirrord_kube::api::container: Pod Phase = "Running"

stdout 2023-05-14T22:26:30.272994Z 49454: pod is ready

stderr 2023-05-14T22:26:30.273298Z 49454: 2023-05-14T22:26:30.273054Z TRACE mirrord_kube::api::kubernetes: port-forward to pod mirrord-agent-5fxbm7qknh-7vjks:43264

stderr 2023-05-14T22:26:30.331964Z 49454: 2023-05-14T22:26:30.331606Z  INFO mirrord_kube::api: mirrord-kube: initiated disconnect from agent

stderr 2023-05-14T22:26:30.332517Z 49454: Error: 

stderr 2023-05-14T22:26:30.333406Z 49454:   × Invalid message received from agent "Some(\n    Close(\n        \"Failed
  │ to create TcpStealerApi: StealerCommand sender failed with `channel
  │ closed`.\",\n    ),\n)"

stderr 2023-05-14T22:26:30.334356Z 49454:   help: This is a bug. Please report it in our Discord or GitHub repository.
        
        - If you're still stuck:
        
        >> Please open a new bug report at https://github.com/metalbear-co/
        mirrord/issues/new/choose
        
        >> Or join our Discord https://discord.gg/metalbear and request help
        in #mirrord-help
        
        >> Or email us at hi@metalbear.co
        
        


mirrord done running.
Found agent job. Verifying its completion before moving on.
Deleting resource `pytest-echo-5zifj0o`
Deleting resource `pytest-echo-5zifj0o`
Deleting resource `random-namespace-7imdanu`
thread 'pause::pause::unpause_after_error' panicked at 'Timeout 25s expired', /Users/mehularora/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rstest-0.17.0/src/timeout.rs:42:21
stack backtrace:
   0: rust_begin_unwind
             at /rustc/478cbb42b730ba4739351b72ce2aa928e78e2f81/library/std/src/panicking.rs:577:5
   1: core::panicking::panic_fmt
             at /rustc/478cbb42b730ba4739351b72ce2aa928e78e2f81/library/core/src/panicking.rs:67:14
   2: rstest::timeout::execute_with_timeout_async::{{closure}}
             at /Users/mehularora/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rstest-0.17.0/src/timeout.rs:42:21
   3: tests::pause::pause::unpause_after_error::{{closure}}
             at ./src/pause.rs:140:5
   4: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/478cbb42b730ba4739351b72ce2aa928e78e2f81/library/core/src/future/future.rs:125:9
   5: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /Users/mehularora/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/park.rs:283:63
   6: tokio::runtime::coop::with_budget
             at /Users/mehularora/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/coop.rs:107:5
   7: tokio::runtime::coop::budget
             at /Users/mehularora/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/coop.rs:73:5
   8: tokio::runtime::park::CachedParkThread::block_on
             at /Users/mehularora/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/park.rs:283:31
   9: tokio::runtime::context::BlockingRegionGuard::block_on
             at /Users/mehularora/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/context.rs:315:13
  10: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at /Users/mehularora/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/scheduler/multi_thread/mod.rs:66:9
  11: tokio::runtime::runtime::Runtime::block_on
             at /Users/mehularora/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/runtime.rs:304:45
  12: tests::pause::pause::unpause_after_error
             at ./src/pause.rs:140:5
  13: tests::pause::pause::unpause_after_error::{{closure}}
             at ./src/pause.rs:140:5
  14: core::ops::function::FnOnce::call_once
             at /rustc/478cbb42b730ba4739351b72ce2aa928e78e2f81/library/core/src/ops/function.rs:250:5
  15: core::ops::function::FnOnce::call_once
             at /rustc/478cbb42b730ba4739351b72ce2aa928e78e2f81/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test pause::pause::unpause_after_error ... FAILED

failures:

failures:
    pause::pause::unpause_after_error

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 56 filtered out; finished in 25.12s

error: test failed, to rerun pass `-p tests --lib`

 *  The terminal process "cargo 'test', '--package', 'tests', '--lib', '--', 'pause::pause::unpause_after_error', '--exact', '--nocapture'" terminated with exit code: 101. 
 ```
 
The current flake happens because when the resources are being cleared, the test just times out while it is supposed to be "success". I think the only fix in this situation is to increase the timeout on the test by ~ 5 seconds

**Comment by eyalb181** [comment]
What's the timeout now?

**Comment by infiniteregrets** [comment]
> What's the timeout now?

I think the timeout can be 65 seconds
