### ISSUE TITLE
Deploy mirrord rust-docs to gh-pages action fails due to `protoc` not being available.

### ISSUE THREAD

**Issue by meowjesty** [metalbear-co/mirrord#1322]
### Bug Description

The github action that builds + publishes our docs fails with:

```sh
Documenting proc-macro-error v1.0.4
error: failed to run custom build command for `containerd-client v0.2.0 (https://github.com/containerd/rust-extensions?rev=16e9695e80bb8da47b5db44fd4a22821c54a2f67#16e9695e)`
```

Due to `"Could not find protoc installation (...)"`.

We need to add it as a CI dependency to CI.

### Steps to Reproduce

1. Run CI action for "deploy mirrord rust-docs".

### Backtrace

```shell
--- stderr
  thread 'main' panicked at 'Could not find `protoc` installation and this build crate cannot proceed without
      this knowledge. If `protoc` is installed and this crate had trouble finding
      it, you can set the `PROTOC` environment variable with the specific path to your
      installed `protoc` binary.If you're on debian, try `apt-get install protobuf-compiler` or download it from https://github.com/protocolbuffers/protobuf/releases

  For more information: https://docs.rs/prost-build/#sourcing-protoc
  ', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/prost-build-0.11.9/src/lib.rs:1457:10
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/478cbb42b730ba4739351b72ce2aa928e78e2f81/library/std/src/panicking.rs:577:5
     1: core::panicking::panic_fmt
               at /rustc/478cbb42b730ba4739351b72ce2aa928e78e2f81/library/core/src/panicking.rs:67:14
     2: core::panicking::panic_display
               at /rustc/478cbb42b730ba4739351b72ce2aa928e78e2f81/library/core/src/panicking.rs:150:5
     3: core::panicking::panic_str
               at /rustc/478cbb42b730ba4739351b72ce2aa928e78e2f81/library/core/src/panicking.rs:134:5
     4: core::option::expect_failed
               at /rustc/478cbb42b730ba4739351b72ce2aa928e78e2f81/library/core/src/option.rs:2057:5
     5: core::option::Option<T>::expect
     6: prost_build::protoc_from_env
     7: prost_build::Config::compile_protos
     8: tonic_build::prost::Builder::compile_with_config
     9: tonic_build::prost::Builder::compile
    10: build_script_build::main
```

### Relevant Logs

[CI logs](https://github.com/metalbear-co/mirrord/actions/runs/4735403030/jobs/8405583157#step:4:375)

### Your operating system and version

CI

### Local process

CI action

**Comment by meowjesty** [comment]
We are failing to install it with [logs](https://github.com/metalbear-co/mirrord/actions/runs/4736972035/jobs/8409204138#step:2:36):

```sh
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
```

**Comment by meowjesty** [comment]
CI passes and docs are building again.
