### ISSUE TITLE
Flaky test `target::target::mirrord_ls`

### ISSUE THREAD

**Issue by meowjesty** [metalbear-co/mirrord#1342]
### Bug Description

CI (e2e docker) failed on test `target::target::mirrord_ls`.

[CI failure](https://github.com/metalbear-co/mirrord/actions/runs/4759221035/jobs/8458386504#step:36:120)

### Steps to Reproduce

Run e2e test

### Relevant Logs

```shell
failures:

---- target::target::mirrord_ls stdout ----
2023-04-20T22:13:18.986849340Z creating service "http-echo" in namespace "default"
2023-04-20T22:13:29.132785175Z done creating service "http-echo" in namespace "default"
executed mirrord with args ["ls"] pid 26356
thread 'target::target::mirrord_ls' panicked at 'called `Result::unwrap()` on an `Err` value: Error("EOF while parsing a value", line: 1, column: 0)', tests/src/target.rs:18:66
stack backtrace:
   0: rust_begin_unwind
             at /rustc/478cbb42b730ba4739351b72ce2aa928e78e2f81/library/std/src/panicking.rs:577:5
   1: core::panicking::panic_fmt
             at /rustc/478cbb42b730ba4739351b72ce2aa928e78e2f81/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/478cbb42b730ba4739351b72ce2aa928e78e2f81/library/core/src/result.rs:1752:5
   3: core::result::Result<T,E>::unwrap
   4: tests::target::target::mirrord_ls::{{closure}}::mirrord_ls::{{closure}}
   5: tests::target::target::mirrord_ls::{{closure}}
   6: <core::pin::Pin<P> as core::future::future::Future>::poll
   7: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
   8: tokio::runtime::park::CachedParkThread::block_on
   9: tokio::runtime::context::BlockingRegionGuard::block_on
  10: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
  11: tokio::runtime::runtime::Runtime::block_on
  12: tests::target::target::mirrord_ls
  13: tests::target::target::mirrord_ls::{{closure}}
  14: core::ops::function::FnOnce::call_once
  15: core::ops::function::FnOnce::call_once
             at /rustc/478cbb42b730ba4739351b72ce2aa928e78e2f81/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stdout 2023-04-20T22:13:29.180079966Z 26356: ["pod/http-echo-6onfogo-7d449c7c46-hr7mk","pod/mirrord-http-log-requester-7947848c94-x4kk2","pod/mirrord-tests-http-logger-5696547454-4qxvt","pod/tcp-echo-6i5lnox-5579d569b-lc77v"]

Deleting resource `http-echo-6onfogo`
Deleting resource `http-echo-6onfogo`
```

### Your operating system and version

CI

### Local process

CI action

**Comment by t4lz** [comment]
Another case: https://github.com/metalbear-co/mirrord/actions/runs/4984747834/jobs/8923676932#step:36:122

Seems like there was no output on stdout after running `mirrord ls`.
Maybe a first step here would be to add some logs to the relevant code (and maybe some prints to the test) and set the log level to `trace` so that we can get some mirrord logs next time this test fails.

**Comment by infiniteregrets** [comment]
> Another case: https://github.com/metalbear-co/mirrord/actions/runs/4984747834/jobs/8923676932#step:36:122
> 
> Seems like there was no output on stdout after running `mirrord ls`. Maybe a first step here would be to add some logs to the relevant code (and maybe some prints to the test) and set the log level to `trace` so that we can get some mirrord logs next time this test fails.

Thanks, ill prioritize this

**Comment by eyalb181** [comment]
Haven't seen this in a while, so closing. Reopen if it recurs.
