### ISSUE TITLE
DNS Resolve fails Spring Boot macOS

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord#1458]
### Bug Description

User complains that their Spring Boot service fails to resolve DNS.

### Steps to Reproduce

Use this repository, have a Redis server in the cluster with service name `redis-man`
https://github.com/aviramha/issue-1458

### Relevant Logs

```shell
2023-05-25 04:04:03.602 ERROR [progression-svc,,] 89301 --- [           main] i.n.r.d.DnsServerAddressStreamProviders  : Unable to load io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider, fallback to system defaults. This may result in incorrect DNS resolutions on MacOS. Check whether you have a dependency on 'io.netty:netty-resolver-dns-native-macos'. Use DEBUG level to see the full stack: java.lang.UnsatisfiedLinkError: failed to load the required native library
```

```
Caused by: io.lettuce.core.RedisConnectionException: Unable to connect to keydb.island-milestone-infra.svc/<unresolved>:6379
        at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:78)
        at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:56)
        at io.lettuce.core.AbstractRedisClient.getConnection(AbstractRedisClient.java:330)
        at io.lettuce.core.RedisClient.connect(RedisClient.java:216)
        at org.springframework.data.redis.connection.lettuce.StandaloneConnectionProvider.lambda$getConnection$1(StandaloneConnectionProvider.java:115)
        at java.base/java.util.Optional.orElseGet(Optional.java:364)
        at org.springframework.data.redis.connection.lettuce.StandaloneConnectionProvider.getConnection(StandaloneConnectionProvider.java:115)
        at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$ExceptionTranslatingConnectionProvider.getConnection(LettuceConnectionFactory.java:1595)
        ... 86 more
Caused by: io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Failed to resolve 'keydb.island-milestone-infra.svc' and search domain query for configured domains failed as well: [router]
````
```


### Your operating system and version

macOS

### Local process

Spring Boot

### Local process version

_No response_

### Additional Info

_No response_

**Comment by clrxbl** [comment]
This appears to be related to Netty's DNS resolver which uses additional native libraries on macOS: https://github.com/netty/netty/tree/4.1/resolver-dns-native-macos

This issue doesn't appear when Netty's DNS resolvers are excluded from the application, but that's a temporary workaround at best.

**Comment by aviramha** [comment]
Seems like netty resolves itself and we don't intercept the socket.

**Comment by aviramha** [comment]
Okay, debugged it further - it seems that it requires `sendto` which means we need to support non-connected UDP sockets
https://github.com/metalbear-co/mirrord/issues/647
