### ISSUE TITLE
IDEA Ultimate freezes when using mirrord

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord#1466]
[threadDump-20230525-085318.txt](https://github.com/metalbear-co/mirrord/files/11564790/threadDump-20230525-085318.txt)

```
2023-05-25 11:26:17,131 [ 493787]   FINE - mirrord - updateJavaParameters called
2023-05-25 11:26:17,131 [ 493787]   FINE - mirrord - Check if relevant
2023-05-25 11:26:17,131 [ 493787]   FINE - mirrord - wsl check
2023-05-25 11:26:17,131 [ 493787]   FINE - mirrord - getting env
2023-05-25 11:26:17,131 [ 493787]   FINE - mirrord - calling start
2023-05-25 11:26:17,132 [ 493788]   FINE - mirrord - version check trigger
2023-05-25 11:26:18,121 [ 494777]   FINE - mirrord - target selection
2023-05-25 11:26:18,147 [ 494803]   FINE - mirrord - target not selected, showing dialog
2023-05-25 11:26:18,147 [ 494803]   FINE - mirrord - executing on pooled thread
2023-05-25 11:29:30,011 [ 686667]   INFO - sun.awt.AWTThreading - InvocationEvent has timed out (awaiting 1555 ms). Originated at java.desktop/sun.lwawt.macosx.CAccessibility.accessibilityHitTest(CAccessibility.java:481)
2023-05-25 11:29:32,009 [ 688665]   INFO - sun.awt.AWTThreading - InvocationEvent has timed out (awaiting 1993 ms). Originated at java.desktop/sun.lwawt.macosx.CAccessibility.getAccessibleRole(CAccessibility.java:286)
2023-05-25 11:30:04,010 [ 720666]   INFO - sun.awt.AWTThreading - InvocationEvent has timed out (awaiting 1890 ms). Originated at java.desktop/sun.lwawt.macosx.CAccessibility.accessibilityHitTest(CAccessibility.java:481)
2023-05-25 11:30:06,006 [ 722662]   INFO - sun.awt.AWTThreading - InvocationEvent has timed out (awaiting 1995 ms). Originated at java.desktop/sun.lwawt.macosx.CAccessibility.getAccessibleRole(CAccessibility.java:286)
2023-05-25 11:30:08,009 [ 724665]   INFO - sun.awt.AWTThreading - InvocationEvent has timed out (awaiting 2001 ms). Originated at java.desktop/sun.lwawt.macosx.CAccessibility.getAccessibleRole(CAccessibility.java:286)
2023-05-25 11:30:10,009 [ 726665]   INFO - sun.awt.AWTThreading - InvocationEvent has timed out (awaiting 1991 ms). Originated at java.desktop/sun.lwawt.macosx.CAccessibility.getAccessibleComponent(CAccessibility.java:348)
```
Debugging a Spring application on macOS

**Comment by aviramha** [comment]
Happens only when debugging mirrord..
