### ISSUE TITLE
dotnet on vscode - errors/closes connection

### ISSUE THREAD

**Issue by infiniteregrets** [metalbear-co/mirrord#1578]
### Bug Description

On the cluster:

App A has two services B and C, A sends request to C which is written in dotnet, on debugging local version of C with vscode with mirrord on, I get the following error:

```
Request: GET /api/v1
Loaded '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Diagnostics.StackTrace.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Reflection.Metadata.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Collections.Immutable.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Request: GET /api/v2
Request: GET /api/v1
Exception thrown: 'System.Net.HttpListenerException' in System.Net.HttpListener.dll
Unhandled exception. System.Net.HttpListenerException (0x80131620): Unable to write data to the transport connection: Broken pipe.
   at System.Net.HttpResponseStream.InternalWrite(Byte[] buffer, Int32 offset, Int32 count)
   at System.Net.HttpResponseStream.WriteCore(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.HttpResponseStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at Program.SendResponse(HttpListenerResponse response, String responseString) in /Users/mehularora/Documents/discord-demo/logger-service/Program.cs:line 74
   at Program.Main(String[] args) in /Users/mehularora/Documents/discord-demo/logger-service/Program.cs:line 50
```

**on some more experimentation, i found that if I set a breakpoint and step slowly, it works okay and receives traffic just fine, but immediately stepping, closes the connection.**

### Steps to Reproduce

(ill share a complete reproducable soon)

the dotnet program:
```cs
using System.Net;
using System.Text;

class Program
{
    static void Main(string[] args)
    {
        string url = "http://*:8080/";
        HttpListener listener = new HttpListener();
        listener.Prefixes.Add(url);
        listener.Start();
        Console.WriteLine("Listening on {0}", url);

        while (true)
        {
            HttpListenerContext context = listener.GetContext();
            HttpListenerRequest request = context.Request;

            if (request.HttpMethod == "GET")

            {
                if (request.Headers["service-log"] == "true")
                {
                    string logMessage = string.Format(
                        "{0} - {1} {2}",
                        DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss"),
                        request.HttpMethod,
                        request.RawUrl);

                    LogToFile("output.txt", logMessage);
                    string responseString = "service-logger logged the request";
                    SendResponse(context.Response, responseString);
                }
                else if (request.Headers["service-log"] == "false")
                {
                    string responseString = "service-logger did not log the request";
                    SendResponse(context.Response, responseString);
                }
                else
                {
                    string? endpoint = request.Url?.AbsolutePath;
                    if (endpoint == "/api/v1")
                    {
                        string responseString = "API v1 endpoint";
                        SendResponse(context.Response, responseString);
                    }
                    else if (endpoint == "/api/v2")
                    {
                        string responseString = "API v2 endpoint";
                        SendResponse(context.Response, responseString);
                    }
                    else
                    {
                        context.Response.StatusCode = (int)HttpStatusCode.NotFound;
                        context.Response.Close();
                    }
                }

                Console.WriteLine("Request: {0} {1}", request.HttpMethod, request.RawUrl, request.Headers["service-log"]);
            }
            else
            {
                context.Response.StatusCode = (int)HttpStatusCode.MethodNotAllowed;
                context.Response.Close();
            }
        }
    }

    static void SendResponse(HttpListenerResponse response, string responseString)
    {
        byte[] buffer = Encoding.UTF8.GetBytes(responseString);
        response.ContentLength64 = buffer.Length;
        Stream output = response.OutputStream;
        output.Write(buffer, 0, buffer.Length);
        output.Close();
    }

    static void LogToFile(string filePath, string logMessage)
    {
        using (StreamWriter writer = File.AppendText(filePath))
        {
            writer.WriteLine(logMessage);
        }
    }
}
```

### Backtrace

```shell
first request:

Request: GET /api/v1
2023-06-20T19:57:50.758193Z  WARN ThreadId(02) tcp_tunnel: mirrord_layer::tcp_mirror: tcp_tunnel -> exiting due to remote stream closed! local_stream=PollEvented { io: Some(TcpStream { addr: 127.0.0.1:51336, peer: 127.0.0.1:8080, fd: 67 }) }
2023-06-20T19:57:50.758259Z DEBUG ThreadId(02) tcp_tunnel: mirrord_layer::tcp_mirror: tcp_tunnel -> exiting local_stream=PollEvented { io: Some(TcpStream { addr: 127.0.0.1:51336, peer: 127.0.0.1:8080, fd: 67 }) }
2023-06-20T19:57:50.758389Z TRACE ThreadId(02) tcp_tunnel: mirrord_layer::tcp_mirror: close time.busy=382µs time.idle=1.07s local_stream=PollEvented { io: Some(TcpStream { addr: 127.0.0.1:51336, peer: 127.0.0.1:8080, fd: 67 }) }

then ping pong
```

### Your operating system and version

uname -a Darwin mehuls-air.lan 21.4.0 Darwin Kernel Version 21.4.0: Mon Feb 21 20:36:53 PST 2022; root:xnu-8020.101.4~2/RELEASE_ARM64_T8101 arm64

### Local process

dotnet --info .NET SDK:  Version:   7.0.302  Commit:    990cf98a27  Runtime Environment:  OS Name:     Mac OS X  OS Version:  12.3  OS Platform: Darwin  RID:         osx.12-arm64  Base Path:   /usr/local/share/dotnet/sdk/7.0.302/  Host:   Version:      7.0.5   Architecture: arm64   Commit:       8042d61b17  .NET SDKs installed:   7.0.302 [/usr/local/share/dotnet/sdk]  .NET runtimes installed:   Microsoft.AspNetCore.App 7.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]   Microsoft.NETCore.App 7.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]  Other architectures found:   None  Environment variables:   Not set  global.json file:   Not found  Learn more:   https://aka.ms/dotnet/info  Download .NET:   https://aka.ms/dotnet/download

**Comment by aviramha** [comment]
I assume that it tries to write to a connection that was closed because it's mirroring (i.e the remote already responded and closed it). This should be solvable by separating write closure and read closure (`socket shutdown`).

**Comment by infiniteregrets** [comment]
> I assume that it tries to write to a connection that was closed because it's mirroring (i.e the remote already responded and closed it). This should be solvable by separating write closure and read closure (`socket shutdown`).

makes sense, could be the case, ill give it a try

**Comment by eyalb181** [comment]
@infiniteregrets Are you still working on this?

**Comment by infiniteregrets** [comment]
@aviramha explained that this is okay to happen in mirroring
