### ISSUE TITLE
outgoing e2e flake

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord#1862]
```
error: test failed, to rerun pass `-p mirrord-layer --test outgoing`
test outgoing_tcp::with_config_2_Some___outgoing_filter_json___ ... FAILED
test outgoing_tcp_from_the_local_app_broken::with_config_1_Some___outgoing_filter_local_json___ - should panic ... ok

failures:

---- outgoing_tcp::with_config_2_Some___outgoing_filter_json___ stdout ----
Listening for messages from the layer on 127.0.0.1:49356
using config file: /Users/runner/work/mirrord/mirrord/mirrord/layer/tests/configs/outgoing_filter.json
Using executable: /Users/runner/work/mirrord/mirrord/mirrord/layer/../../target/debug/outgoing
Using args: ["--tcp", "4.4.4.4:4444", "1.1.1.1:1111,2.2.2.2:2222,3.3.3.3:3333"]
Started application.
Got connection from library.
stderr 06:07:56 8732: 2023-08-28T06:07:56.193157Z  INFO ThreadId(01) mirrord_layer: Initializing mirrord-layer!

Got connection from layer.
stderr 06:07:56 8732: 2023-08-28T06:07:56.196754Z  INFO ThreadId(01) mirrord_layer::socket::ops: in connect LazyLock(
    {
        10: UserSocket {
            id: SocketId(
                0,
            ),
            domain: 2,
            type_: 1,
            protocol: 0,
            state: Initialized,
            kind: Tcp(
                1,
            ),
        },
    },
)
2023-08-28T06:07:56.196950Z DEBUG ThreadId(01) resolve_dns: mirrord_layer::socket: new self=Remote({OutgoingFilter { protocol: Any, address: Socket(0.0.0.0:3333) }, OutgoingFilter { protocol: Any, address: Socket(2.2.2.2:2222) }, OutgoingFilter { protocol: Tcp, address: Subnet((1.1.1.0/24, 1111)) }})
2023-08-28T06:07:56.197023Z DEBUG ThreadId(01) resolve_dns: mirrord_layer::socket: return=Ok({}) self=Remote({OutgoingFilter { protocol: Any, address: Socket(0.0.0.0:3333) }, Outgoi
stderr 06:07:56 8732: ngFilter { protocol: Any, address: Socket(2.2.2.2:2222) }, OutgoingFilter { protocol: Tcp, address: Subnet((1.1.1.0/24, 1111)) }})

stderr 06:07:56 8732: 2023-08-28T06:07:56.199955Z DEBUG ThreadId(01) resolve_dns: mirrord_layer::socket: close time.busy=1.51ms time.idle=1.50ms self=Remote({OutgoingFilter { protocol: Any, address: Socket(0.0.0.0:3333) }, OutgoingFilter { protocol: Any, address: Socket(2.2.2.2:2222) }, OutgoingFilter { protocol: Tcp, address: Subnet((1.1.1.0/24, 1111)) }})

stderr 06:07:56 8732: 2023-08-28T06:07:56.203061Z  WARN ThreadId(02) mirrord_layer::outgoing::tcp: interceptor_task -> exiting due to remote stream closed!

stderr 06:07:56 8732: 2023-08-28T06:07:56.203290Z  INFO ThreadId(01) mirrord_layer::socket::ops: in connect LazyLock(
    {
        10: UserSocket {
            id: SocketId(
                1,
            ),
            domain: 2,
            type_: 1,
            protocol: 0,
            state: Initialized,
            kind: Tcp(
                1,
            ),
        },
    },
)
2023-08-28T06:07:56.203358Z DEBUG ThreadId(01) resolve_dns: mirrord_layer::socket: new self=Remote({OutgoingFilter { protocol: Any, address: Socket(0.0.0.0:3333) }, OutgoingFilter { protocol: Any, address: Socket(2.2.2.2:2222) }, OutgoingFilter { protocol: Tcp, address: Subnet((1.1.1.0/24, 1111)) }})

stderr 06:07:56 8732: 2023-08-28T06:07:56.203401Z DEBUG ThreadId(01) resolve_dns: mirrord_layer::socket: return=Ok({}) self=Remote({OutgoingFilter { protocol: Any, address: Socket(0.0.0.0:3333) }, OutgoingFilter { protocol: Any, address: Socket(2.2.2.2:2222) }, OutgoingFilter { protocol: Tcp, address: Subnet((1.1.1.0/24, 1111)) }})
2023-08-28T06:07:56.203455Z DEBUG ThreadId(01) resolve_dns: mirrord_layer::socket: close time.busy=57.4µs time.idle=39.6µs self=Remote({OutgoingFilter { protocol: Any, address: Socket(0.0.0.0:3333) }, OutgoingFilter { protocol: Any, address: Socket(2.2.2.2:2222) }, OutgoingFilter { protocol: Tcp, address: Subnet((1.1.1.0/24, 1111)) }})

stderr 06:07:56 8732: 2023-08-28T06:07:56.204750Z  WARN ThreadId(02) mirrord_layer::outgoing::tcp: interceptor_task -> exiting due to remote stream closed!

stderr 06:07:56 8732: 2023-08-28T06:07:56.204931Z  INFO ThreadId(01) mirrord_layer::socket::ops: in connect LazyLock(
    {
        10: UserSocket {
            id: SocketId(
                2,
            ),
            domain: 2,
            type_: 1,
            protocol: 0,
            state: Initialized,
            kind: Tcp(
                1,
            ),
        },
    },
)
2023-08-28T06:07:56.204998Z DEBUG ThreadId(01) resolve_dns: mirrord_layer::socket: new self=Remote({OutgoingFilter { protocol: Any, address: Socket(0.0.0.0:3333) }, OutgoingFilter { protocol: Any, address: Socket(2.2.2.2:2222) }, OutgoingFilter { protocol: Tcp, address: Subnet((1.1.1.0/24, 1111)) }})
2023-08-28T06:07:56.205026Z DEBUG ThreadId(01) resolve_dns: mirrord_layer::socket: return=Ok({}) self=Remote({OutgoingFilter { protocol: Any, address: Socket(0.0.0.0:3333) }, Outgoi
stderr 06:07:56 8732: ngFilter { protocol: Any, address: Socket(2.2.2.2:2222) }, OutgoingFilter { protocol: Tcp, address: Subnet((1.1.1.0/24, 1111)) }})

stderr 06:07:56 8732: 2023-08-28T06:07:56.205051Z DEBUG ThreadId(01) resolve_dns: mirrord_layer::socket: close time.busy=27.9µs time.idle=26.6µs self=Remote({OutgoingFilter { protocol: Any, address: Socket(0.0.0.0:3333) }, OutgoingFilter { protocol: Any, address: Socket(2.2.2.2:2222) }, OutgoingFilter { protocol: Tcp, address: Subnet((1.1.1.0/24, 1111)) }})

waiting for process to exit
stderr 06:07:56 8732: 2023-08-28T06:07:56.206224Z  WARN ThreadId(02) mirrord_layer::outgoing::tcp: interceptor_task -> exiting due to remote stream closed!

process exit, waiting for stdout/err to be read
thread 'outgoing_tcp::with_config_2_Some___outgoing_filter_json___' panicked at 'Timeout 10s expired', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rstest-0.17.0/src/timeout.rs:42:21
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c609da59d9fc05b1c7dc879d79700ccd8140b5fc/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/c609da59d9fc05b1c7dc879d79700ccd8140b5fc/library/core/src/panicking.rs:67:14
   2: rstest::timeout::execute_with_timeout_async::{{closure}}
   3: outgoing::outgoing_tcp::with_config_2_Some___outgoing_filter_json___::{{closure}}
   4: <core::pin::Pin<P> as core::future::future::Future>::poll
   5: <core::pin::Pin<P> as core::future::future::Future>::poll
   6: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}::{{closure}}
   7: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}
   8: tokio::runtime::scheduler::current_thread::Context::enter
   9: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}
  10: tokio::runtime::scheduler::current_thread::CoreGuard::enter::{{closure}}
  11: tokio::runtime::context::scoped::Scoped<T>::set
  12: tokio::runtime::context::set_scheduler::{{closure}}
  13: std::thread::local::LocalKey<T>::try_with
  14: std::thread::local::LocalKey<T>::with
  15: tokio::runtime::context::set_scheduler
  16: tokio::runtime::scheduler::current_thread::CoreGuard::enter
  17: tokio::runtime::scheduler::current_thread::CoreGuard::block_on
  18: tokio::runtime::scheduler::current_thread::CurrentThread::block_on::{{closure}}
  19: tokio::runtime::context::runtime::enter_runtime
  20: tokio::runtime::scheduler::current_thread::CurrentThread::block_on
  21: tokio::runtime::runtime::Runtime::block_on
  22: outgoing::outgoing_tcp::with_config_2_Some___outgoing_filter_json___
  23: outgoing::outgoing_tcp::with_config_2_Some___outgoing_filter_json___::{{closure}}
  24: core::ops::function::FnOnce::call_once
  25: core::ops::function::FnOnce::call_once
             at /rustc/c609da59d9fc05b1c7dc879d79700ccd8140b5fc/library/core/src/ops/function.rs:[250](https://github.com/metalbear-co/mirrord/actions/runs/5996166233/job/16260268386?pr=1833#step:37:251):5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by infiniteregrets** [comment]
looking into the test and running it locally, i saw the test is decorated with #[should_panic], so im not sure whats the issue here?

**Comment by infiniteregrets** [comment]
Seems like this hasnt happened in a while nor i am able to reproduce it locally, but as @aviramha mentioned before there is a real bug here and is blocked on the protocol change, so will for that to happen to retest

**Comment by aviramha** [comment]
It could've been fixed by the intproxy overhaul.

**Comment by eyalb181** [comment]
Closing for now, reopen if reproduces.
