### ISSUE TITLE
Unable to use mirrord on Java Service with connection to Kafka and MongoDB

### ISSUE THREAD

**Issue by JuergetSTatVGOA** [metalbear-co/mirrord#2205]
### Bug Description

Hello

I tried to use mirrord on a Java (Spring Boot) service which is connected to Kafka and MongoDB.
The Service is using Spring Kafka Streams and the regular MongoDB Client.
Though, env mirroring and dns resolving seems to work, I get `Network is unreachable` Exceptions when starting up the Kafka Client and also MongoDB Client is unable to create the connection.

My configuration File is:

{
    "feature": {
        "network": {
            "incoming": "mirror",
            "outgoing": {
                "ignore_localhost": true,
            },
            "dns": true
        },
        "fs": "read",
        "env": true
    },
    "target": {
        "path": {
            "deployment": "$SERVICE_NAME"
        },
        "namespace": "$NAMESPACE"
    },
    "agent": {
        "log_level": "mirrord=info,warn"
    },
    "kube_context": "$CONTEXT",
    "telemetry": false
}

Exceptions appear independently of using mirrord as standalone or plugin in IntelliJ

### Steps to Reproduce

1. mirrord exec -f .mirrord/mirrord.json java -- -jar build/libs/service.jar 

### Backtrace

```shell
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:579)
	at java.base/sun.nio.ch.Net.connect(Net.java:586)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:853)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:277)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:255)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:990)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:301)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.trySend(ConsumerNetworkClient.java:498)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:255)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:236)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:215)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:246)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.coordinatorUnknownAndUnready(ConsumerCoordinator.java:460)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:488)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1262)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1231)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1211)
	at org.apache.kafka.streams.processor.internals.StreamThread.pollRequests(StreamThread.java:980)
	at org.apache.kafka.streams.processor.internals.StreamThread.pollPhase(StreamThread.java:933)
	at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:751)
	at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:604)
	at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:576)
```

### Your operating system and version

Mac OS Sonoma 14.3, Apple Silicone M1 Java 17

### Local process

java,  Version 17

**Comment by aviramha** [comment]
Hi,
Sorry about the troubles. Can you please re-run with trace logs ?
`MIRRORD_PROGRESS_MODE=off RUST_LOG=mirrord=trace mirrord exec -f .mirrord/mirrord.json java -- -jar build/libs/service.jar`

Please make sure to take out any sensitive information from the logs before attaching.
If you'd like, we can also schedule a screen share session using this [link](https://calendly.com/aviram-5/30min).

**Comment by JuergetSTatVGOA** [comment]
Hello, sorry for answering that late, but here a the output of the command.
Seems to be a permission problem 

```
024-02-05T13:42:43.140986Z  INFO mirrord: Launching "java" with arguments ["-jar", "build/libs/service.jar"]
2024-02-05T13:42:47.180654Z TRACE start:create_and_connect:create_session:fetch_operator: mirrord_operator::client: return=Err(KubeError { error: HyperError(hyper::Error(Connect, Custom { kind: Other, error: Os { code: 54, kind: ConnectionReset, message: "Connection reset by peer" } })), operation: FindingOperator })
2024-02-05T13:42:47.181049Z TRACE start:create_and_connect: mirrord::connection: Failed to connect to the operator, probably due to RBAC: finding operator failed: HyperError: error trying to connect: Connection reset by peer (os error 54)
2024-02-05T13:42:51.222277Z DEBUG start:create_and_connect: mirrord::connection: couldn't determine OpenShift: mirrord-layer: Kube failed with error `HyperError: error trying to connect: Connection reset by peer (os error 54)`!
Error:   × Create agent failed. KubeError(
  │     HyperError(
  │         hyper::Error(
  │             Connect,
  │             Custom {
  │                 kind: Other,
  │                 error: Os {
  │                     code: 54,
  │                     kind: ConnectionReset,
  │                     message: "Connection reset by peer",
  │                 },
  │             },
  │         ),
  │     ),
  │ )
```

**Comment by JuergetSTatVGOA** [comment]
Thank's for your answer.
When trying today, to gather the trace logs, it worked like a charm.
Though I really don't know why :-)
I'll close this issue !
