### ISSUE TITLE
Issues connecting to redis in k8s using redisson/netty

### ISSUE THREAD

**Issue by scottillogical** [metalbear-co/mirrord#2443]
### Bug Description

When running a java app using redisson and connecting to a redis instance in a k8s namespace, dns resolution fails

```
024-05-14 09:28:29.148 DEBUG redisson-netty-2-2 - [io.netty.resolver.dns.DnsQueryContext] [id: 0xba9751dc] WRITE: UDP, [26484: /127.0.0.1:59915], DefaultDnsQuestion(cheetah-redis-master.scott1.svc.cluster.local. IN CNAME)
2024-05-14 09:28:29.351 DEBUG redisson-netty-2-2 - [io.netty.resolver.dns.DnsNameResolver] [id: 0xba9751dc] RECEIVED: UDP [26484: /127.0.0.1:59915], DatagramDnsResponse(from: /127.0.0.1:59915, to: /0.0.0.0:54438, 26484, QUERY(0), NXDomain(3), RD)
    DefaultDnsQuestion(cheetah-redis-master.scott1.svc.cluster.local. IN CNAME)
2024-05-14 09:28:29.398 DEBUG redisson-netty-2-2 - [io.netty.buffer.PoolThreadCache] Freed 2 thread-local buffer(s) from thread: redisson-netty-2-2
CheetahException starting the cheetah:illegal_state: org.redisson.client.RedisConnectionException - java.net.UnknownHostException: Failed to resolve 'cheetah-redis-master.scott1.svc.cluster.local' [A(1)] after 2 queries
```

### Steps to Reproduce

1. Deploy redis to k8s cluster
2. Run java app using redisson to connect to redis via mirrord
3. Observe dns failure

example at 
https://github.com/scottillogical/mirrord-netty-redis-bug

### Backtrace

```shell
Exception in thread "main" java.net.UnknownHostException: failed to resolve 'cheetah-redis-master.scott-mirrord-test.svc.cluster.local' after 2 queries 
	at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:901)
	at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:860)
	at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:328)
	at io.netty.resolver.dns.DnsResolveContext.onResponse(DnsResolveContext.java:515)
	at io.netty.resolver.dns.DnsResolveContext.access$400(DnsResolveContext.java:63)
	at io.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:372)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:502)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:495)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:474)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:415)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:540)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:529)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:101)
	at io.netty.resolver.dns.DnsQueryContext.setSuccess(DnsQueryContext.java:196)
	at io.netty.resolver.dns.DnsQueryContext.finish(DnsQueryContext.java:188)
	at io.netty.resolver.dns.DnsNameResolver$DnsResponseHandler.channelRead(DnsNameResolver.java:1182)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:682)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:617)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:534)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:750)
```

### Your operating system and version

mac os 13.6.3

### Local process

java

### Additional Info

asked in discord https://discord.com/channels/933706914808889356/950020257156833340/1239935262646341653

**Comment by aviramha** [comment]
I tested it, the issue reproduces with IntelilJ but seems to work from cli - this looks like a SIP issue since I don't see logs when using IDEA.

**Comment by scottillogical** [comment]
Hm I was able to reproduce via the cli with our internal app.  It works fine for other services (postgres, rmq etc, on services that do not require redis to boot) so I was figuring it was isolated to the netty dns resolution codepath.  See output below.  Also when I comment out the redis codepath on boot, everything works fine - it connects to rabbitmq it the cluster etc.

I tried to set the example app up to be able to reproduce in the cli via gradle run but was not able to though I'm sure someone more proficient in java/gradle could modify my example to work via cli


```
$| mirrord exec -n scott1 -a scott1 --target deployment/gateway java -- -jar gateway-server-6.295.0-6.295.0.jar
When targeting multi-pod deployments, mirrord impersonates the first pod in the deployment.
Support for multi-pod impersonation requires the mirrord operator, which is part of mirrord for Teams.
You can get started with mirrord for Teams at this link: https://mirrord.dev/docs/overview/teams/
⠴ mirrord exec
    ✓ Running on latest (3.101.0)!
    ✓ ready to launch process
      ✓ layer extracted
      ✓ operator not found
      ✓ agent pod created
      ✓ pod is ready
Caused by: java.net.UnknownHostException: failed to resolve 'cheetah-redis-master.scott1.svc.cluster.local' after 2 queries
        at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:901)
        at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:860)
        at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:328)
        at io.netty.resolver.dns.DnsResolveContext.onResponse(DnsResolveContext.java:515)
        at io.netty.resolver.dns.DnsResolveContext.access$400(DnsResolveContext.java:63)
        at io.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:372)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:502)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:495)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:474)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:415)
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:540)
        at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:529)
        at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:101)
        at io.netty.resolver.dns.DnsQueryContext.setSuccess(DnsQueryContext.java:196)
        at io.netty.resolver.dns.DnsQueryContext.finish(DnsQueryContext.java:188)
        at io.netty.resolver.dns.DnsNameResolver$DnsResponseHandler.channelRead(DnsNameResolver.java:1182)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
        at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:682)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:617)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:534)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:750)
```

**Comment by aviramha** [comment]
Can't reproduce it :(
Would you like to schedule a session to debug it together?
You can pick time with me [here](https://calendly.com/aviram-5/30min).

**Comment by scottillogical** [comment]
Debugged on the call and the issue was a conflict with telepresence dns.  Running telepresence quit resolved the issue
