### ISSUE TITLE
Mirrord fails to connect with Proxy error, connectivity issue or bug 

### ISSUE THREAD

**Issue by edison-vflow** [metalbear-co/mirrord#2697]
### Bug Description

When connecting to pods in a K8 cluster, we get an error

![image](https://github.com/user-attachments/assets/7c423a36-013d-4df9-9673-92ab6f78bcf2)

### Steps to Reproduce

run mirrord connecting command to cluster 

### Relevant Logs

```shell
agent ready - version 3.115.1
2024-08-22T18:00:35.884973Z  WARN ThreadId(07) mirrord_agent::outgoing::udp: interceptor_task -> no messages left
2024-08-22T18:01:24.743478Z  WARN ThreadId(04) mirrord_agent::steal::ip_tables::flush_connections: `conntrack` output is Output {
    status: ExitStatus(
        unix_wait_status(
            256,
        ),
    ),
    stdout: "",
    stderr: "conntrack v1.4.7 (conntrack-tools): 0 flow entries have been updated.\n",
}
2024-08-22T18:01:32.547378Z ERROR ThreadId(04) mirrord_agent::steal::connections::filtered: Failed connecting to request destination error=Os { code: 111, kind: ConnectionRefused, message: "Connection refused" } address=127.0.0.1:8013
2024-08-22T18:01:32.548350Z ERROR ThreadId(04) mirrord_agent::steal::connections::filtered: Failed connecting to request destination error=Os { code: 111, kind: ConnectionRefused, message: "Connection refused" } address=127.0.0.1:8013
2024-08-22T18:01:32.607032Z  WARN ThreadId(04) mirrord_agent::steal::ip_tables::flush_connections: `conntrack` output is Output {
    status: ExitStatus(
        unix_wait_status(
            256,
        ),
    ),
    stdout: "",
    stderr: "conntrack v1.4.7 (conntrack-tools): 0 flow entries have been updated.\n",
}
2024-08-22T18:01:42.551145Z ERROR ThreadId(04) mirrord_agent::steal::connections::filtered: Failed connecting to request destination error=Os { code: 111, kind: ConnectionRefused, message: "Connection refused" } address=127.0.0.1:8013
2024-08-22T18:01:42.551322Z ERROR ThreadId(04) mirrord_agent::steal::connections::filtered: Failed connecting to request destination error=Os { code: 111, kind: ConnectionRefused, message: "Connection refused" } address=127.0.0.1:8013
2024-08-22T18:01:52.548717Z ERROR ThreadId(04) mirrord_agent::steal::connections::filtered: Failed connecting to request destination error=Os { code: 111, kind: ConnectionRefused, message: "Connection refused" } address=127.0.0.1:8013
2024-08-22T18:01:52.548900Z ERROR ThreadId(04) mirrord_agent::steal::connections::filtered: Failed connecting to request destination error=Os { code: 111, kind: ConnectionRefused, message: "Connection refused" } address=127.0.0.1:8013
2024-08-22T18:02:02.546751Z ERROR ThreadId(04) mirrord_agent::steal::connections::filtered: Failed connecting to request destination error=Os { code: 111, kind: ConnectionRefused, message: "Connection refused" } address=127.0.0.1:8013
2024-08-22T18:02:12.548454Z ERROR ThreadId(04) mirrord_agent::steal::connections::filtered: Failed connecting to request destination error=Os { code: 111, kind: ConnectionRefused, message: "Connection refused" } address=127.0.0.1:8013
2024-08-22T18:02:26.488038Z ERROR ThreadId(15) mirrord_agent::util: Failed setting pid 1565914 namespace "net" with FailedNamespaceOpen(
    Os {
        code: 2,
        kind: NotFound,
        message: "No such file or directory",
    },
)
thread 'DNS worker' panicked at mirrord/agent/src/util.rs:145:42:
Failed setting namespace!: FailedNamespaceEnter(FailedNamespaceOpen(Os { code: 2, kind: NotFound, message: "No such file or directory" }))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2024-08-22T18:02:26.988515Z ERROR ThreadId(16) mirrord_agent::util: Failed setting pid 1565914 namespace "net" with FailedNamespaceOpen(
    Os {
        code: 2,
        kind: NotFound,
        message: "No such file or directory",
    },
)
thread 'DNS worker' panicked at mirrord/agent/src/util.rs:145:42:
Failed setting namespace!: FailedNamespaceEnter(FailedNamespaceOpen(Os { code: 2, kind: NotFound, message: "No such file or directory" }))
2024-08-22T18:02:27.547030Z ERROR ThreadId(04) mirrord_agent::steal::connections::filtered: Failed connecting to request destination error=Os { code: 111, kind: ConnectionRefused, message: "Connection refused" } address=127.0.0.1:8013
2024-08-22T18:02:32.548697Z ERROR ThreadId(04) mirrord_agent::steal::connections::filtered: Failed connecting to request destination error=Os { code: 111, kind: ConnectionRefused, message: "Connection refused" } address=127.0.0.1:8013
```

### Your operating system and version

MacOS Sonoma

### Local process

nodejs

### Local process version

20

**Comment by aviramha** [comment]
Hi,
My guess would be the remote pod restarts/terminates and so the mirrord-agent dies. Can you provide your mirrord.json please and check if my guess is correct?

**Comment by xavidop** [comment]
yeah, it seems that the pod gets restarted when we are using mirrors:
<img width="755" alt="image" src="https://github.com/user-attachments/assets/0c2e442a-4ed9-4ffa-b92d-f475cc46e7a2">

this is only happening with that service, we exclude the /health service, check the mirrored.json file:
```json
{
  "feature": {
    "env": true,
    "fs": {
      "mode": "{{ get_env(name="FS_MODE", default="read") }}",
      "read_only": [ "^/secrets/.*" ]
    },
    "network": {
      "dns": {{ get_env(name="DNS_MODE", default=true) }},
      "outgoing": {{ get_env(name="OUTGOING_MODE", default=true) }},
      "incoming": {
        "mode": "{{ get_env(name="INCOMING_MODE", default="steal") }}",
        "port_mapping": {{ get_env(name="PORT_MAPPING", default="[[8080, 8001]]") }},
        "listen_ports":  {{ get_env(name="PORT_MAPPING", default="[[8080, 8001]]") }},
        "http_filter": {
          "path_filter": "^(?!/health)",
          "ports": {{ get_env(name="LIST_MAPPING", default="[8080]") }}
        }
      }
    }
  },
  "internal_proxy": {
    "log_destination": "/tmp/mirrord.log",
    "log_level": "mirrord=info"
  },
  "agent": {
    "check_out_of_pods": false
  },
  "experimental": {
    "readlink": true
  }
}
```
Do you know what could be happening?

**Comment by aviramha** [comment]
can you describe the pod/deployment and see the restart reason?

**Comment by xavidop** [comment]
We have deleted the deployment and re-created it back again. the issue is gone for now. I know we had another engineer who had this issue back in the past too. Can we keep this issue opened so we can come here and updated when this happened again?

**Comment by aviramha** [comment]
Most likely happened due to pod restart, which is working as intended (without operator).
