### ISSUE TITLE
Add IntelliJ extension to mirrord.dev

### ISSUE THREAD

**Issue by eyalb181** [metalbear-co/mirrord#280]

**Comment by simobgl** [comment]
Why is the Jetbrains plugin no more available?

**Comment by eyalb181** [comment]
Hey @simobgl, it should be available [here](https://plugins.jetbrains.com/plugin/19772-mirrord). Note that our first stable version, 2.9.0, should be released tomorrow.

**Comment by simobgl** [comment]
many thanks

**Comment by simobgl** [comment]
I tried it yesterday with no success, has the stable been released? this is a very interesting project

**Comment by infiniteregrets** [comment]
hi @simobgl, could you please share more information regarding what errors you faced while running your project with mirrord? Perhaps, the IDE error and the environment configuration you chose would be helpful! We can probably get on discord and discuss if that's comfortable (:

**Comment by eyalb181** [comment]
Closing this issue since it refers to adding details about the extension to our website. However feel free to continue the discussion here, in our Discussions section, or on Discord.

**Comment by simobgl** [comment]
Nothing happens, the mirrord button on the toolbar is pressed, I try to launch a debug session and was expecting a dialog but it's stuck there. MacOs 11.6 with Goland 2022.2.2

**Comment by eyalb181** [comment]
@simobgl Just to make sure, you don't get an error notification in the IDE right? Is kubectl configure properly, are you able to run `kubectl get pods`?

**Comment by simobgl** [comment]
cluster connection verifies, got an error:
java.lang.reflect.UndeclaredThrowableException
	at jdk.proxy2/jdk.proxy2.$Proxy209.processStarting(Unknown Source)
	at com.intellij.execution.impl.ExecutionManagerImpl$doStartRunProfile$startRunnable$1.run(ExecutionManagerImpl.kt:223)

but it is probable due to kluster permissions, I'll try again with a cluster I have full control of

**Comment by infiniteregrets** [comment]
Hi @simobgl I was able to reproduce the error you got, 
```
java.lang.reflect.UndeclaredThrowableException
	at jdk.proxy2/jdk.proxy2.$Proxy179.processStarting(Unknown Source)
	at com.intellij.execution.impl.ExecutionManagerImpl$doStartRunProfile$startRunnable$1.run(ExecutionManagerImpl.kt:223)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:513)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:75)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:118)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: io.kubernetes.client.openapi.ApiException: java.net.ConnectException: Failed to connect to /127.0.0.1:60553
	at io.kubernetes.client.openapi.ApiClient.execute(ApiClient.java:888)
	at io.kubernetes.client.openapi.apis.CoreV1Api.listNamespaceWithHttpInfo(CoreV1Api.java:29879)
	at io.kubernetes.client.openapi.apis.CoreV1Api.listNamespace(CoreV1Api.java:29772)
	at com.metalbear.mirrord.KubeDataProvider.getNamespaces(KubeDataProvider.kt:12)
	at com.metalbear.mirrord.MirrordListener.processStarting(MirrordListener.kt:38)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:649)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:625)
	at com.intellij.util.messages.impl.MessageBusImplKt.deliverMessage(MessageBusImpl.kt:399)
	at com.intellij.util.messages.impl.MessageBusImplKt.pumpWaiting(MessageBusImpl.kt:378)
	at com.intellij.util.messages.impl.MessageBusImplKt.access$pumpWaiting(MessageBusImpl.kt:1)
	at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:437)
	... 33 more
```
This happens when you're not connected to a valid cluster, for example using minikube but minikube is not running.
But the extension still won't support mirrord properly for golang since there is an issue with env vars(#298 #308) which we are working on. However, feel free to send any feedback if you get a chance to try this with any other language/framework! Thank you (:

**Comment by simobgl** [comment]
Many thanks for your follow-up. I'm very interested in using this with golang. Is there a way to be notified when the issue will be solved? that would be great for many organizations I work with

**Comment by infiniteregrets** [comment]
For sure, this should be resolved soon! I will notify you as soon as a new version with the patch is out (: Thanks!

**Comment by infiniteregrets** [comment]
hi @simobgl, we just had an alpha release for mirrord with support for goland macos/linux. You can download the release from here https://plugins.jetbrains.com/plugin/19772-mirrord/versions/alpha/227480 and manually install it in preference -> plugins -> settings icon -> install from disk.
Let us know if you need any help! Thanks (:
