### ISSUE TITLE
Another AF_INET6 regression

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord#2835]
```
mirrord_layer::socket::ops: connect -> Failed call to libc::connect with ConnectResult {
    result: -1,
    error: Some(
        Errno {
            code: 22,
            description: Some(
                "Invalid argument",
            ),
        },
    ),
}
```

```
2024-10-14T07:29:14.656711Z ERROR ThreadId(01) mirrord_layer::socket::ops: connect -> Failed call to libc::connect with ConnectResult {
    result: -1,
    error: Some(
        Errno {
            code: 47,
            description: Some(
                "Address family not supported by protocol family",
            ),
        },
    ),
}
```

**Comment by aviramha** [comment]
Way of reproducing

```
mirrord exec -- python3
* Running binary "python3" with arguments: [].
* mirrord will run without a target, no configuration file was loaded
* operator: the operator will be used if possible
* env: all environment variables will be fetched
* fs: file operations will default to read only from the remote
* incoming: incoming traffic will be mirrored
* outgoing: forwarding is enabled on TCP and UDP
* dns: DNS will be resolved remotely
⠤ mirrord exec
    ✓ running on latest (3.120.0)!
    ✓ ready to launch process
      ✓ layer extracted
      ✓ using operator
        ✓ operator version compatible
        ✓ operator license valid
        ✓ user credentials prepared
        ✓ session started
          ✓ connected to the target
    ✓ config summary                                                                                                                                                                        Python 3.11.7 (main, Jan 11 2024, 12:00:32) [Clang 15.0.0 (clang-1500.0.40.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> s = socket.socket(socket.AF_INET6, socket.SOCK_STREAM)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'socket' is not defined
>>> import socket
>>> s = socket.socket(socket.AF_INET6, socket.SOCK_STREAM)
>>> s.connect(("8.8.8.8", 80))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: [Errno 99] Not a STREAM
```
