### ISSUE TITLE
`connect` fails when dealing with IPv6 (agent errors with `AddrNotAvailable`)

### ISSUE THREAD

**Issue by meowjesty** [metalbear-co/mirrord#377]
### Bug Description

The outgoing traffic feature fails when a request is made for an IPv6 address, as the pod doesn't support it (apparently).

This may cause issues when resolving a DNS to some IPv6 address.

### Steps to Reproduce

1. Make a request resolving the address as IPv6;
2. Crashes.

### Backtrace

```shell
file:///home/lanedraex/dev/metalbear/mirrord/tests/node-e2e/outgoing/test_outgoing_traffic_single_request.mjs:32
  throw fail;
  ^

Error: connect Unknown system error -74 2600:9000:238e:c00:::443 - Local (:::0)
    at internalConnect (node:net:959:16)
    at defaultTriggerAsyncIdScope (node:internal/async_hooks:463:18)
    at GetAddrInfoReqWrap.emitLookup [as callback] (node:net:1105:9)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:85:8) {
  errno: -74,
  code: 'Unknown system error -74',
  syscall: 'connect',
  address: '2600:9000:238e:c00::',
  port: 443
}

Node.js v18.0.0
```

### Relevant Logs

- agent:

```shell
2022-09-08T18:15:32.761900Z DEBUG mirrord_agent: main -> Initializing mirrord-agent.
2022-09-08T18:15:32.762055Z DEBUG mirrord_agent: starting with args Args { container_id: Some("5136357f7dcf3c5dec30d61ab067e53579d4fa583dcfca0ff4fa70cd0009c9a5"), container_runtime: Some("docker"), communicate_port: 48791, communication_timeout: 30, interface: "eth0", ephemeral_container: false }
2022-09-08T18:15:32.764296Z  INFO mirrord_agent: agent ready
2022-09-08T18:15:32.765776Z DEBUG mirrord_agent::runtime: set_namespace -> fd 18
2022-09-08T18:15:32.765779Z DEBUG mirrord_agent::runtime: set_namespace -> fd 19
2022-09-08T18:15:32.765894Z DEBUG mirrord_agent::sniffer: preparing sniffer
2022-09-08T18:15:32.765899Z DEBUG mirrord_agent::sniffer: prepare_sniffer -> Preparing interface.
2022-09-08T18:15:33.632075Z DEBUG mirrord_agent: start -> Connection accepted from 127.0.0.1:59892
2022-09-08T18:15:33.632284Z DEBUG mirrord_agent::file: Agent root path >> "/proc/3512/root"
2022-09-08T18:15:33.633563Z DEBUG mirrord_agent::runtime: set_namespace -> fd 35
2022-09-08T18:15:33.633601Z DEBUG mirrord_agent::steal: preparing steal
2022-09-08T18:15:33.633730Z DEBUG mirrord_agent::runtime: set_namespace -> fd 42
2022-09-08T18:15:33.634059Z DEBUG mirrord_agent::runtime: set_namespace -> fd 43
2022-09-08T18:15:33.667335Z DEBUG mirrord_agent: client_handler -> client sent message GetEnvVarsRequest(GetEnvVarsRequest { env_vars_filter: {}, env_vars_select: {"*"} })
2022-09-08T18:15:33.667368Z DEBUG mirrord_agent: ClientMessage::GetEnvVarsRequest client id 0 filter {} select {"*"}
2022-09-08T18:15:33.814231Z DEBUG mirrord_agent::steal: finished preparing steal
2022-09-08T18:15:33.894930Z DEBUG mirrord_agent: client_handler -> client sent message GetAddrInfoRequest(GetAddrInfoRequest { node: Some("www.rust-lang.org"), service: None, hints: Some(AddrInfoHint { ai_family: 10, ai_socktype: 1, ai_protocol: 0, ai_flags: 0 }) })
2022-09-08T18:15:33.971792Z DEBUG mirrord_agent: client_handler -> client sent message TcpOutgoing(Connect(LayerConnect { remote_address: [2600:9000:238e:9800::]:443 }))
2022-09-08T18:15:33.984744Z DEBUG mirrord_agent: Client 0 disconnected
2022-09-08T18:15:33.984774Z DEBUG mirrord_agent: client closing
2022-09-08T18:15:33.984877Z DEBUG mirrord_agent::sniffer: packet_worker -> empty ports, setting dummy bpf
2022-09-08T18:15:33.984898Z DEBUG mirrord_agent: ClientConnectionHandler::start -> Client 0 disconnected
2022-09-08T18:15:33.984905Z  WARN mirrord_agent::outgoing: interceptor_task -> no messages left
2022-09-08T18:15:33.984917Z  WARN mirrord_agent::outgoing::udp: interceptor_task -> no messages left
2022-09-08T18:15:33.985258Z DEBUG mirrord_agent::steal: rx closed, breaking
2022-09-08T18:15:33.985377Z DEBUG mirrord_agent::steal: TCP Stealer exiting
2022-09-08T18:15:33.985395Z DEBUG mirrord_agent::steal: steal exiting
```

- layer:

```shell
2022-09-08T18:04:26.912413Z DEBUG mirrord_layer::socket::ops: connect -> sockfd 26 | remote_address [2600:9000:238e:c00::]:443
2022-09-08T18:04:26.912462Z TRACE mirrord_layer::socket::ops: connect -> SocketState::Initialized UserSocket {
    domain: 10,
    type_: 526337,
    protocol: 0,
    state: Initialized,
    kind: Tcp(
        526337,
    ),
}
2022-09-08T18:04:26.912685Z TRACE mirrord_layer: Layer::handle_hook_message -> hook_message TcpOutgoing(Connect(Connect { remote_address: [2600:9000:238e:c00::]:443, channel_tx: Sender { inner: Some(Inner { state: State { is_complete: false, is_closed: false, is_rx_task_set: true, is_tx_task_set: false } }) } }))
2022-09-08T18:04:26.912786Z TRACE mirrord_layer::outgoing::tcp: handle_hook_message -> message Connect(Connect { remote_address: [2600:9000:238e:c00::]:443, channel_tx: Sender { inner: Some(Inner { state: State { is_complete: false, is_closed: false, is_rx_task_set: true, is_tx_task_set: false } }) } })
2022-09-08T18:04:26.912859Z TRACE mirrord_layer::outgoing::tcp: Connect -> remote_address [2600:9000:238e:c00::]:443
2022-09-08T18:04:26.915100Z TRACE mirrord_layer::outgoing::tcp: handle_daemon_message -> message Connect(Err(RemoteIO(RemoteIOError { raw_os_error: Some(99), kind: AddrNotAvailable })))
2022-09-08T18:04:26.915240Z TRACE mirrord_layer::outgoing::tcp: Connect -> connect Err(
    RemoteIO(
        RemoteIOError {
            raw_os_error: Some(
                99,
            ),
            kind: AddrNotAvailable,
        },
    ),
)
2022-09-08T18:04:26.915316Z ERROR mirrord_layer: Error handling daemon message: ResponseError(RemoteIO(RemoteIOError { raw_os_error: Some(99), kind: AddrNotAvailable }))
2022-09-08T18:04:26.915474Z ERROR mirrord_layer::error: Error occured in Layer >> RecvError(RecvError(()))
2022-09-08T18:04:26.915729Z TRACE mirrord_layer::socket::hooks: getsockname_detour -> sockfd 26
2022-09-08T18:04:26.915801Z TRACE mirrord_layer::socket::ops: getsockname -> sockfd 26
2022-09-08T18:04:26.917462Z TRACE mirrord_layer::socket::hooks: fcntl_detour -> fd 2 | cmd 3
2022-09-08T18:04:26.917603Z TRACE mirrord_layer::socket::hooks: fcntl_detour -> result 32769
2022-09-08T18:04:26.917682Z TRACE mirrord_layer::file::hooks: open_detour -> open_flags 524545
2022-09-08T18:04:26.917756Z TRACE mirrord_layer::socket::hooks: dup3_detour -> oldfd 27 | newfd 2 | flags 524288
2022-09-08T18:04:26.917802Z TRACE mirrord_layer::socket::hooks: dup3_detour -> result 2
>> request failed with Error: connect Unknown system error -74 2600:9000:238e:c00:::443 - Local (:::0)
```

### Your operating system and version

Windows 10 wsl (Ubuntu 20.04.4 LTS)

### Local process

[test_outgoing_traffic_single_request_ipv6.mjs](https://github.com/meowjesty/mirrord/blob/fix-ipv6/tests/node-e2e/outgoing/test_outgoing_traffic_single_request_ipv6.mjs)

**Comment by meowjesty** [comment]
Alright, this behaves exactly the same in the pod (no more `Unknown system error`):

- pod

```sh
>> test_outgoing_traffic_single_request_ipv6
>> request failed with Error: connect EADDRNOTAVAIL 2600:9000:238e:f200:14:513f:eb40:93a1:443 - Local (:::0)
file:///root/dev/request-ipv6.mjs:35
  throw fail;
  ^

Error: connect EADDRNOTAVAIL 2600:9000:238e:f200:14:513f:eb40:93a1:443 - Local (:::0)
    at internalConnect (net.js:924:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:364:12)
    at GetAddrInfoReqWrap.emitLookup [as callback] (net.js:1060:9)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:68:8) {
  errno: 'EADDRNOTAVAIL',
  code: 'EADDRNOTAVAIL',
  syscall: 'connect',
  address: '2600:9000:238e:f200:14:513f:eb40:93a1',
  port: 443
}
```

- local app (preloaded)

```sh
>> request failed with Error: connect EADDRNOTAVAIL 2600:9000:238e:2800:::443 - Local (:::0)
2022-09-26T16:37:47.635379Z TRACE ThreadId(01) write_logic{fd=27 count=93}: mirrord_layer::file::hooks: exit
test_outgoing_traffic_single_request_ipv6.mjs:35
  throw fail;
  ^

Error: connect EADDRNOTAVAIL 2600:9000:238e:2800:::443 - Local (:::0)
    at internalConnect (node:net:959:16)
    at defaultTriggerAsyncIdScope (node:internal/async_hooks:463:18)
    at GetAddrInfoReqWrap.emitLookup [as callback] (node:net:1105:9)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:85:8) {
  errno: -99,
  code: 'EADDRNOTAVAIL',
  syscall: 'connect',
  address: '2600:9000:238e:2800::',
  port: 443
}

```
