### ISSUE TITLE
Application gets RSTs on outgoing TCP sessions.

### ISSUE THREAD

**Issue by t4lz** [metalbear-co/mirrord#564]
### Bug Description

The application gets resets which lead to a `ECONNRESET`.
I couldn't locate the cause neither in the layer's nor in the agent's logs, so I think maybe the RSTs originate with the layer (the layer drops the connection early and a RST is sent to the app on the mirror stream).

### Steps to Reproduce

It only reproduced on the CI, and only in twice out of thousands of outgoing requests.
Triggering the CI on this request https://github.com/metalbear-co/mirrord/pull/553 is almost guaranteed to lead to an error at some point, but you would probably have to try it a couple of times until you get this specific error (or change it in some way to keep running the test after one try has failed, like a simple way would be to duplicate the e2e job, so you get 1 error per job.)

### Backtrace

```shell
Type A:

Error: Client network socket disconnected before secure TLS connection was established
    at connResetException (internal/errors.js:639:14)
    at TLSSocket.onConnectEnd (_tls_wrap.js:1570:19)
    at TLSSocket.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  code: 'ECONNRESET',
  path: null,
  host: 'www.youtube.com',
  port: 443,
  localAddress: undefined
}

Type B:

Error: socket hang up
    at connResetException (internal/errors.js:639:14)
    at TLSSocket.socketOnEnd (_http_client.js:499:23)
    at TLSSocket.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  code: 'ECONNRESET'
}
```

### Your operating system and version

Ubuntu 20.04.5 LTS

### Local process

node

### Local process version

14

**Comment by eyalb181** [comment]
Retest when #1470 is completed.

**Comment by aviramha** [comment]
test
