### ISSUE TITLE
intellij-ext: mirrord doesn't work when the service account doesn't have permissions to list namespaces

### ISSUE THREAD

**Issue by seferino-fernandez** [metalbear-co/mirrord#678]
### Bug Description

Hello! I have limited access to a work cluster and one of the permissions I'm lacking is the ability to list namespaces (https://github.com/metalbear-co/mirrord/blob/main/intellij-ext/src/main/kotlin/com/metalbear/mirrord/MirrordListener.kt#L42).

I'm wondering if you can add some type of handling to either get the current namespace only, or allow user input to specify the namespace.

Thanks!

### Steps to Reproduce

1. Create a service account that doesn't have LIST permissions to namespaces.
2. Set your current context to use that service account.
3. Use IntelliJ and enable the mirrord plugin.
4. Run your application.

### Relevant Logs

```shell
When you run your application, you will get an error notification saying: "Error occurred while fetching namespaces from Kubernetes context"
```

### Your operating system and version

macOS Monterey 12.6

### Local process

IntelliJ + Mirrord Extension

### Additional Info

I have access to list the pods from the current namespace like so `kubectl get pods --namespace=test-namespace` just not able to do `kubectl get namespaces`.

**Comment by eyalb181** [comment]
Hey @seferino-fernandez , thanks for reporting! It's definitely doable, we'll let you know when the fix is released.

**Comment by infiniteregrets** [comment]
hey @seferino-fernandez, we just released a possible fix for this issue. will you be able to test it out if possible? Thank you!

**Comment by seferino-fernandez** [comment]
Hey @infiniteregrets, thanks for the quick update and support!

Unfortunately I'm now seeing another error.
After I enable mirrord and run my application, I get the error message:
```
Error occurred while fetching namespaces from Kubernetes context. mirrord will use the default namespace from kube configuration. ``
```

Here is the stack trace that I get:
```java
java.nio.file.NoSuchFileException: /var/run/secrets/kubernetes.io/serviceaccount/namespace
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:380)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:432)
	at java.base/java.nio.file.Files.readAllBytes(Files.java:3288)
	at io.kubernetes.client.util.Namespaces.getPodNamespace(Namespaces.java:31)
	at com.metalbear.mirrord.KubeDataProvider.getPodNamespace(KubeDataProvider.kt:19)
	at com.metalbear.mirrord.MirrordListener.processStartScheduled$lambda-2(MirrordListener.kt:66)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:513)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:75)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:118)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:918)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:766)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:450)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:449)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:624)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:447)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```
I tried reinstalling the plugin but no luck.

**Comment by infiniteregrets** [comment]
hey @seferino-fernandez, thanks for checking again! We are introducing an extension-specific env var `DEFAULT_POD_NAMESPACE `, which will allow you to specify the namespace you want to get pods from. by default, this is set to "default", you can override this before running mirrord. I will keep you posted as soon as a new release with the patch is out!

**Comment by seferino-fernandez** [comment]
Thanks again @eyalb181 and @infiniteregrets for the support!

I was able to get past this and connect to kubernetes!
