### ISSUE TITLE
Support `go run` as an exec target

### ISSUE THREAD

**Issue by gshaibi** [metalbear-co/mirrord#862]
Hi guys,

First of all, your software is awesome!
Currently I'm building my executable in advance and pass it to the `mirrord exec` command.
It would really make my life easier if I could  run `mirrord exec go run ./cmd/main.go ...` instead.

**Comment by aviramha** [comment]
Thank you!
I wonder, what happens when you try to mirrord go run? I think I know few reasons why it won't work but want to make sure.

**Comment by infiniteregrets** [comment]
```
023-01-02T02:35:45.566674Z TRACE ThreadId(05) openat: mirrord_layer::file::ops: enter fd=-100 rawish_path=Some("/dev/null") open_options=OpenOptionsInternal { read: true, write: false, append: false, truncate: false, create: false, create_new: false }
2023-01-02T02:35:45.566740Z TRACE ThreadId(05) openat:open: mirrord_layer::file::ops: enter fd=-100 rawish_path=Some("/dev/null") open_options=OpenOptionsInternal { read: true, write: false, append: false, truncate: false, create: false, create_new: false } rawish_path=Some("/dev/null") open_options=OpenOptionsInternal { read: true, write: false, append: false, truncate: false, create: false, create_new: false }
2023-01-02T02:35:45.568210Z TRACE ThreadId(01) openat:open: mirrord_layer::file::ops: exit fd=-100 rawish_path=Some("/dev/null") open_options=OpenOptionsInternal { read: true, write: false, append: false, truncate: false, create: false, create_new: false } rawish_path=Some("/dev/null") open_options=OpenOptionsInternal { read: true, write: false, append: false, truncate: false, create: false, create_new: false }
2023-01-02T02:35:45.568290Z TRACE ThreadId(01) openat: mirrord_layer::file::ops: exit fd=-100 rawish_path=Some("/dev/null") open_options=OpenOptionsInternal { read: true, write: false, append: false, truncate: false, create: false, create_new: false }
2023-01-02T02:35:45.568365Z TRACE ThreadId(01) mirrord_layer::go_hooks: c_abi_syscall_handler: syscall=293 param1=824635189824 param2=524288 param3=0
2023-01-02T02:35:45.568416Z TRACE ThreadId(01) mirrord_layer::go_hooks: c_abi_syscall_handler: syscall=72 param1=14 param2=3 param3=0
2023-01-02T02:35:45.568442Z TRACE ThreadId(01) mirrord_layer::go_hooks: c_abi_syscall_handler: syscall=72 param1=14 param2=4 param3=2048
2023-01-02T02:35:45.568468Z TRACE ThreadId(01) mirrord_layer::go_hooks: c_abi_syscall_handler: syscall=72 param1=15 param2=3 param3=0
2023-01-02T02:35:45.568490Z TRACE ThreadId(01) mirrord_layer::go_hooks: c_abi_syscall_handler: syscall=72 param1=15 param2=4 param3=2049
2023-01-02T02:35:45.568515Z TRACE ThreadId(01) mirrord_layer::go_hooks: c_abi_syscall_handler: syscall=293 param1=824635189816 param2=524288 param3=0
2023-01-02T02:35:45.568545Z TRACE ThreadId(01) mirrord_layer::go_hooks: c_abi_syscall_handler: syscall=72 param1=16 param2=3 param3=0
2023-01-02T02:35:45.568571Z TRACE ThreadId(01) mirrord_layer::go_hooks: c_abi_syscall_handler: syscall=72 param1=16 param2=4 param3=2048
2023-01-02T02:35:45.568596Z TRACE ThreadId(01) mirrord_layer::go_hooks: c_abi_syscall_handler: syscall=72 param1=17 param2=3 param3=0
2023-01-02T02:35:45.568618Z TRACE ThreadId(01) mirrord_layer::go_hooks: c_abi_syscall_handler: syscall=72 param1=17 param2=4 param3=2049
2023-01-02T02:35:45.568667Z TRACE ThreadId(01) mirrord_layer::go_hooks: c_abi_syscall_handler: syscall=72 param1=15 param2=3 param3=0
2023-01-02T02:35:45.568691Z TRACE ThreadId(01) mirrord_layer::go_hooks: c_abi_syscall_handler: syscall=72 param1=15 param2=4 param3=1
2023-01-02T02:35:45.568714Z TRACE ThreadId(01) mirrord_layer::go_hooks: c_abi_syscall_handler: syscall=72 param1=17 param2=3 param3=0
2023-01-02T02:35:45.568736Z TRACE ThreadId(01) mirrord_layer::go_hooks: c_abi_syscall_handler: syscall=72 param1=17 param2=4 param3=1
2023-01-02T02:35:45.568771Z TRACE ThreadId(01) mirrord_layer::go_hooks: c_abi_syscall_handler: syscall=293 param1=824635189472 param2=524288 param3=0
2023-01-02T02:35:45.568946Z TRACE ThreadId(01) mirrord_layer::go_hooks: c_abi_syscall_handler: syscall=292 param1=10 param2=0 param3=0
2023-01-02T02:35:45.569042Z TRACE ThreadId(01) mirrord_layer::go_hooks: c_abi_syscall_handler: syscall=292 param1=15 param2=1 param3=0
fatal: morestack on g0
2023-01-02T02:35:45.569981Z TRACE ThreadId(05) openat:open: mirrord_layer::file::ops: exit fd=-100 rawish_path=Some("/dev/null") open_options=OpenOptionsInternal { read: true, write: false, append: false, truncate: false, create: false, create_new: false } rawish_path=Some("/dev/null") open_options=OpenOptionsInternal { read: true, write: false, append: false, truncate: false, create: false, create_new: false }
2023-01-02T02:35:45.570059Z TRACE ThreadId(05) openat: mirrord_layer::file::ops: exit fd=-100 rawish_path=Some("/dev/null") open_options=OpenOptionsInternal { read: true, write: false, append: false, truncate: false, create: false, create_new: false }
SIGTRAP: trace trap
PC=0x4654e2 m=0 sigcode=128

goroutine 0 [idle]:
runtime.abort()
        /usr/local/go/src/runtime/asm_amd64.s:1036 +0x2
runtime.morestack()
        /usr/local/go/src/runtime/asm_amd64.s:515 +0x25

goroutine 20 [running]:
runtime: unknown pc 0x7f32d2df8ee0
stack: frame={sp:0xc0001665f8, fp:0x0} stack=[0xc000166000,0xc000168000)
0x000000c0001664f8:  0x0000000000000000  0x00007f32d260f2f0 
0x000000c000166508:  0x00007f32d3181c7d  0x000000000000008b 
0x000000c000166518:  0x00007f32d2613240  0x0000000000000000 
0x000000c000166528:  0x00007f32d260f2f0  0x00007f32d2613240 
0x000000c000166538:  0x0000000000000000  0x000000c000166580 
0x000000c000166548:  0x000000c000166590  0x0000000000432bb6 <runtime.setsig+0x0000000000000076> 
0x000000c000166558:  0x0000000000000040  0x000000000047bf80 <syscall.RawSyscall+0x0000000000000000> 
0x000000c000166568:  0xffffffffffffffff  0x000000c000122d00 
0x000000c000166578:  0x0000000000000000  0x00000000004726ed <syscall.forkAndExecInChild1+0x00000000000003ed> 
0x000000c000166588:  0x0000000000000216  0x00007ffc8fd45c68 
0x000000c000166598:  0x00007ffc8fd477a0  0x00007f32d48dab78 
0x000000c0001665a8:  0x0000000000000003  0x0000000000000015 
0x000000c0001665b8:  0x000000c000166828  0x000000c0001665f8 
0x000000c0001665c8:  0x0000000000000002  0x000000c0001da030 
0x000000c0001665d8:  0x000000c0003fc150  0x000000c0000d6900 
0x000000c0001665e8:  0x0000000000000202  0x00007f32d2df7d0c 
0x000000c0001665f8: <0x00000000004726ed <syscall.forkAndExecInChild1+0x00000000000003ed>  0x000000000000003b 
0x000000c000166608:  0x000000c0003fc150  0x0000000000016089 
0x000000c000166618:  0x0000000000000000  0x0000000000000002 
0x000000c000166628:  0x0000000000000000  0x0000000000000000 
0x000000c000166638:  0x0000000000000000  0x0000000000000000 
0x000000c000166648:  0x0000000000000000  0x0000000000000000 
0x000000c000166658:  0x0000000000000000  0x0000000000000000 
0x000000c000166668:  0x0000000000000000  0x0000000000000000 
0x000000c000166678:  0x0000000000000000  0x0000000000015fb8 
0x000000c000166688:  0x0000000000000000  0x0000000000000011 
0x000000c000166698:  0x0000000000000002  0x0000000000000000 
0x000000c0001666a8:  0x000000000237f080  0x0000000000000003 
0x000000c0001666b8:  0x0000000000000000  0x0000000000000000 
0x000000c0001666c8:  0x3d326d6172617020  0x3a72656c646e6168 
0x000000c0001666d8:  0x0000000000000015  0x6d305b1b736b6f6f 
0x000000c0001666e8:  0x305b1b3a6d325b1b  0x2931302864496461 
runtime: unknown pc 0x7f32d2df8ee0
stack: frame={sp:0xc0001665f8, fp:0x0} stack=[0xc000166000,0xc000168000)
0x000000c0001664f8:  0x0000000000000000  0x00007f32d260f2f0 
0x000000c000166508:  0x00007f32d3181c7d  0x000000000000008b 
0x000000c000166518:  0x00007f32d2613240  0x0000000000000000 
0x000000c000166528:  0x00007f32d260f2f0  0x00007f32d2613240 
0x000000c000166538:  0x0000000000000000  0x000000c000166580 
0x000000c000166548:  0x000000c000166590  0x0000000000432bb6 <runtime.setsig+0x0000000000000076> 
0x000000c000166558:  0x0000000000000040  0x000000000047bf80 <syscall.RawSyscall+0x0000000000000000> 
0x000000c000166568:  0xffffffffffffffff  0x000000c000122d00 
0x000000c000166578:  0x0000000000000000  0x00000000004726ed <syscall.forkAndExecInChild1+0x00000000000003ed> 
0x000000c000166588:  0x0000000000000216  0x00007ffc8fd45c68 
0x000000c000166598:  0x00007ffc8fd477a0  0x00007f32d48dab78 
0x000000c0001665a8:  0x0000000000000003  0x0000000000000015 
0x000000c0001665b8:  0x000000c000166828  0x000000c0001665f8 
0x000000c0001665c8:  0x0000000000000002  0x000000c0001da030 
0x000000c0001665d8:  0x000000c0003fc150  0x000000c0000d6900 
0x000000c0001665e8:  0x0000000000000202  0x00007f32d2df7d0c 
0x000000c0001665f8: <0x00000000004726ed <syscall.forkAndExecInChild1+0x00000000000003ed>  0x000000000000003b 
0x000000c000166608:  0x000000c0003fc150  0x0000000000016089 
0x000000c000166618:  0x0000000000000000  0x0000000000000002 
0x000000c000166628:  0x0000000000000000  0x0000000000000000 
0x000000c000166638:  0x0000000000000000  0x0000000000000000 
0x000000c000166648:  0x0000000000000000  0x0000000000000000 
0x000000c000166658:  0x0000000000000000  0x0000000000000000 
0x000000c000166668:  0x0000000000000000  0x0000000000000000 
0x000000c000166678:  0x0000000000000000  0x0000000000015fb8 
0x000000c000166688:  0x0000000000000000  0x0000000000000011 
0x000000c000166698:  0x0000000000000002  0x0000000000000000 
0x000000c0001666a8:  0x000000000237f080  0x0000000000000003 
0x000000c0001666b8:  0x0000000000000000  0x0000000000000000 
0x000000c0001666c8:  0x3d326d6172617020  0x3a72656c646e6168 
0x000000c0001666d8:  0x0000000000000015  0x6d305b1b736b6f6f 
0x000000c0001666e8:  0x305b1b3a6d325b1b  0x2931302864496461 
created by cmd/go/internal/work.(*Builder).Do
        /usr/local/go/src/cmd/go/internal/work/exec.go:187 +0x3da

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc000381440?)
        /usr/local/go/src/runtime/sema.go:56 +0x25
sync.(*WaitGroup).Wait(0x9858a0?)
        /usr/local/go/src/sync/waitgroup.go:136 +0x52
cmd/go/internal/work.(*Builder).Do(0xc0000b1040, {0xaddd78, 0xc000024098}, 0xc00019a140)
        /usr/local/go/src/cmd/go/internal/work/exec.go:210 +0x4af
cmd/go/internal/run.runRun({0xaddd78, 0xc000024098}, 0xc000028510?, {0xc0000201a0?, 0x1, 0x1})
        /usr/local/go/src/cmd/go/internal/run/run.go:166 +0x76d
main.invoke(0xdb8dc0, {0xc000020190, 0x2, 0x2})
        /usr/local/go/src/cmd/go/main.go:218 +0x2ee
main.main()
        /usr/local/go/src/cmd/go/main.go:175 +0x78e

goroutine 21 [runnable]:
os.newFile(0x16?, {0x9df638?, 0x9?}, 0x1?)
        /usr/local/go/src/os/file_unix.go:122 +0x1a9
os.openFileNolog({0x9df638, 0x9}, 0x0, 0x0)
        /usr/local/go/src/os/file_unix.go:240 +0x170
os.OpenFile({0x9df638, 0x9}, 0x0, 0xd1f1c5b8?)
        /usr/local/go/src/os/file.go:338 +0x45
os.Open(...)
        /usr/local/go/src/os/file.go:318
os/exec.(*Cmd).stdin(0xc0003d9080)
        /usr/local/go/src/os/exec/exec.go:246 +0x2ce
os/exec.(*Cmd).Start(0xc0003d9080)
        /usr/local/go/src/os/exec/exec.go:410 +0x266
os/exec.(*Cmd).Run(0x93e2c0?)
        /usr/local/go/src/os/exec/exec.go:338 +0x1e
cmd/go/internal/work.(*Builder).toolID(0xc0000b1040, {0x9de5bb, 0x7})
        /usr/local/go/src/cmd/go/internal/work/buildid.go:167 +0x425
cmd/go/internal/work.(*Builder).buildActionID(0xc0000b1040, 0xc0000c0780)
        /usr/local/go/src/cmd/go/internal/work/exec.go:314 +0xe95
cmd/go/internal/work.(*Builder).build(0xc0000b1040, {0xc000024098?, 0x0?}, 0xc0000c0780)
        /usr/local/go/src/cmd/go/internal/work/exec.go:474 +0x199
cmd/go/internal/work.(*Builder).Do.func2({0xaddd78, 0xc000024098}, 0xc0000c0780)
        /usr/local/go/src/cmd/go/internal/work/exec.go:139 +0x5ec
cmd/go/internal/work.(*Builder).Do.func3()
        /usr/local/go/src/cmd/go/internal/work/exec.go:201 +0xb9
created by cmd/go/internal/work.(*Builder).Do
        /usr/local/go/src/cmd/go/internal/work/exec.go:187 +0x3da

rax    0x17
rbx    0x9e94a7
rcx    0x466eb5
rdx    0x17
rdi    0x2
rsi    0x9e94a7
rbp    0xc000166a20
rsp    0xc0001668e0
r8     0x0
r9     0x0
r10    0x8
r11    0x246
r12    0x4726ed
r13    0x0
r14    0xdc50e0
r15    0xffffffffffffffff
rip    0x4654e2
rflags 0x202
cs     0x33
fs     0x0
gs     0x0
```

**Comment by gshaibi** [comment]
It was my mistake, I should have used mirrord this way:
`mirrord ... -- go run main.go`

Thanks for the quick support!

**Comment by infiniteregrets** [comment]
> It was my mistake, I should have used mirrord this way:
> `mirrord ... -- go run main.go`
> 
> Thanks for the quick support!

So does it work? For me it panicked..
